experimentName: dngo
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 100
trainingServicePlatform: local  # choices: local, remote, pai
searchSpacePath: search_space.json
useAnnotation: false
builtinTunerName: TPE
trial:
  codeDir: nni/examples/trials/mnist-pytorch
  command: python mnist.py
  gpuNum: 1
